fix: exit with error when not detecting package manager

diff --git a/workflow-steps/run-agent/main.yaml b/workflow-steps/run-agent/main.yaml
--- a/workflow-steps/run-agent/main.yaml
+++ b/workflow-steps/run-agent/main.yaml
@@ -13,12 +13,13 @@ definition:
     script: |
       if test -f "$PACKAGE_LOCK_FILEPATH"; then
           echo "Using npm"
-          npm ci
-      fi
-
-      if test -f "$YARN_LOCK_FILEPATH"; then
+          exit
+      elseif test -f "$YARN_LOCK_FILEPATH"; then
           echo "Using yarn"
-          yarn ci
+          yarn
+      elseif
+          echo "Failed to detect package manager"
+          exit 1
       fi
   - name: Run Agent
     env:
